### ISSUE TITLE
Make it part of the multiformats org

### ISSUE THREAD

**Issue by diasdavid** [multiformats/js-mafmt#17]
@whyrusleeping would you be so kind as moving this module to the multiformats org? We use it all over the place and love it, making it part of the org would make it more discoverable and easier to maintain (you know, CI, labels and other updates).

**Comment by diasdavid** [comment]
ping @whyrusleeping

**Comment by diasdavid** [comment]
ping @whyrusleeping

**Comment by whyrusleeping** [comment]
what do you want

**Comment by whyrusleeping** [comment]
@diasdavid are you responding through email or something? Look at the top of the page

**Comment by diasdavid** [comment]
wwwweeeird
