### ISSUE TITLE
Do not throw?

### ISSUE THREAD

**Issue by alanshaw** [multiformats/js-mafmt#25]
`mafmt.HTTP.matches('/ip4/127.0.0.1/tcp/90/http/baz.jpg')` currently throws. Would it be better for consumers of this library if it just returned false?

**Comment by diasdavid** [comment]
👍

**Comment by vmx** [comment]
As mentioned in #53 I think it should return true.

**Comment by alanshaw** [comment]
That specific example aside, what I'm asking is: should any bad multiaddr that causes a throw should be caught and return `false`? I feel like it should.

e.g. `mafmt.HTTP.matches('junk')` -> false

**Comment by mkg20001** [comment]
:tada: PR #36
