### ISSUE TITLE
Exported DNS format seems wonky

### ISSUE THREAD

**Issue by raulk** [multiformats/js-mafmt#40]
The exported DNS format allows for TCP encapsulation, which is weird: https://github.com/multiformats/js-mafmt/blob/master/src/index.js#L25

It was introduced in this PR: https://github.com/multiformats/js-mafmt/pull/14

**Comment by raulk** [comment]
IMO, addresses like `/dns/google.com/tcp/80` belong in the `Reliable` format, not in `DNS`.

**Comment by vasco-santos** [comment]
I also agree that that address should not fall under the `DNS` format, but in `Reliable`...

**Comment by jacobheun** [comment]
Yes, https://github.com/multiformats/js-mafmt/blob/v6.0.7/src/index.js#L25, should just go away. It's already covered in `TCP` which is already part or `Reliable`.

**Comment by vasco-santos** [comment]
I will move that out then

**Comment by raulk** [comment]
Is there a reason DNS addresses are only supported on TCP? It seems they should be supported with other protocols, right?

**Comment by raulk** [comment]
This is what I ended up doing: https://github.com/multiformats/go-multiaddr-fmt/commit/53297ecb1a303d2ef1b549ab22a9d188f5836d82

**Comment by raulk** [comment]
@vasco-santos @jacobheun Another wonky entry: https://github.com/multiformats/js-mafmt/blob/master/src/index.js#L43

**Comment by vasco-santos** [comment]
> This is what I ended up doing: [multiformats/go-multiaddr-fmt@53297ec](https://github.com/multiformats/go-multiaddr-fmt/commit/53297ecb1a303d2ef1b549ab22a9d188f5836d82)

I agree and will add it here!

> @vasco-santos @jacobheun Another wonky entry: https://github.com/multiformats/js-mafmt/blob/master/src/index.js#L43

Thanks for the heads up, I will remove it!

**Comment by jacobheun** [comment]
Fixed in #42
